# Generated by Django 3.2.15 on 2022-11-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelfDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(default='mc@gmail.com', max_length=100)),
                ('phoneNo', models.IntegerField()),
                ('idNo', models.IntegerField()),
                ('typeOfCar', models.CharField(choices=[('S', 'Subaru'), ('P', 'Premio'), ('L', 'Landcruiser Prado'), ('V', 'V8'), ('VT', 'Vitz'), ('M', 'Mazda'), ('B', 'Mercedes Benz')], default='1', max_length=30)),
            ],
        ),
    ]
