# Generated by Django 3.2.15 on 2022-11-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safiri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.CharField(max_length=1000000)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
