# Generated by Django 3.2.15 on 2022-11-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safiri', '0002_postcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcar',
            name='name',
            field=models.CharField(default='subaru', max_length=100),
        ),
        migrations.AlterField(
            model_name='postcar',
            name='description',
            field=models.TextField(max_length=1000000),
        ),
    ]
