# Generated by Django 3.2.15 on 2022-11-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safiri', '0003_auto_20221116_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(default='mc@gmail.com', max_length=100)),
                ('phoneNo', models.IntegerField()),
                ('id_No', models.IntegerField()),
                ('located_At', models.CharField(max_length=100)),
                ('let_Date', models.DateTimeField()),
                ('duration_To_Let', models.CharField(max_length=100)),
                ('type_Of_Car_To_Let', models.CharField(choices=[('S', 'Subaru'), ('P', 'Premio'), ('L', 'Landcruiser Prado'), ('V', 'V8'), ('VT', 'Vitz'), ('M', 'Mazda'), ('B', 'Mercedes Benz')], default='1', max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='selfdrive',
            old_name='idNo',
            new_name='id_No',
        ),
        migrations.RenameField(
            model_name='selfdrive',
            old_name='typeOfCar',
            new_name='type_Of_Car',
        ),
    ]
