# Generated by Django 3.2.15 on 2022-11-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safiri', '0004_auto_20221116_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('no_of_passegers', models.IntegerField()),
                ('your_Location', models.CharField(max_length=100)),
                ('departure_Time', models.DateTimeField()),
                ('distance_to_travel', models.CharField(max_length=100)),
            ],
        ),
    ]
